### ISSUE TITLE
PSP Launcher not working on 2.2.1 (?) - please renew license

### ISSUE THREAD

**Issue by HoshiYamazaki** [PS3Xploit/PS3HEN#11]
I use PS3HEN 2.2.1 and when I try to launch PSP ISO from multiman I get message that I must renew license. I tried two PSP launcher - Cobra (which is working to mount point) and jikyuu - which is not detected by multiman and says:
```PSP Launcher application is not installed!```
So I don't know what I do wrong. Any help appreciated.

**Comment by Joonie86** [comment]
PSP Remasters Launcher 
https://store.brewology.com/get/homebrew.php?id=247&fid=1239

PSP Minis Launcher
https://store.brewology.com/get/homebrew.php?id=247&fid=1179

https://www.psdevwiki.com/ps3/PSP_Emulator_Compatibility_List
PSP on PS3 compatibility chart

**Comment by HoshiYamazaki** [comment]
Ok, everything works fine, I had PS3HEN 2.1.1 installed not 2.2.1, sorry for mistake! Now on 2.2.2 I can play FF7CC :)
