### ISSUE TITLE
Enabling Hen cause freezing over v.2.2.1

### ISSUE THREAD

**Issue by pakkosauna** [PS3Xploit/PS3HEN#13]
Hi.

my console freeze every time i try enabe HEN if i use 2.2.1 of newer version.
I have try install OFW 4.84 again 3 times, but same consequence.
Luckily Enabling HAN Blind Flash can install 2.1.1 version back, whitout start over again.
My ps3 is semi slim Finnish language.
installed Homebrew
WEBman 1.47.20. mod
multiman 4.82
rebubtool 02.03.02
HEN XMB refresh

**Comment by Joonie86** [comment]
Did you disable network? if so try this pkg

http://xmbmods.co/HEN/Latest_HEN_Installer_2.3.0.1_484C.pkg

**Comment by pakkosauna** [comment]
Thanks fast answer.
Playstation network is disabled.
that pkg did not installed at all. when i signed it its stop in 15%.

**Comment by ShaolinAssassin** [comment]
@pakkosauna you need to mount flash as rewrite to install this PKG. Use http://ps3xploit.com/hen/rewrite/ to do that. 

Btw, maybe you should also update wmm to last version ([1.47.24](https://github.com/aldostools/webMAN-MOD/releases/tag/1.47.24)).

**Comment by pakkosauna** [comment]
You i did mount flash as rewrite, that time it did`t work, but now i got it in. it is still freeze.
And i also update wmm.

**Comment by ShaolinAssassin** [comment]
Did you reboot after installing this PKG ?

**Comment by pakkosauna** [comment]
Yes, Got it work, I install LocalSTORE in HAN Blind Flash 
[https://github.com/xps3riments/localSTORE/releases](url)
