### ISSUE TITLE
Check "Star" not lighting up when enabled

### ISSUE THREAD

**Issue by MrNumberSix** [PS3Xploit/PS3HEN#19]
On HFW 4.85, HEN 3.0.0, the "Check" simbol is not lighting up on the options menu when enabling HEN.

**Comment by Joonie86** [comment]
> On HFW 4.85, HEN 3.0.0, the "Check" simbol is not lighting up on the options menu when enabling HEN.

I think that's an expected behavior since the feature requires DEBUG version of VSH. That star should not even show up if the original explore plugin was used, but it was introduced due to a debug version we included for the initial installation process.
