### ISSUE TITLE
PS2 Games not working

### ISSUE THREAD

**Issue by DiogoSilva48** [PS3Xploit/PS3HEN#2]
Hi, since I installed HEN I can't get PS2 Games working at all, tried loading PS2 ISO's, I get crashes or simply errors like Format not compatible, tried old method with HAN to play PS2 Classics, I can install them no problem, but when opening them my ps3 kinda of turns off, the TV says "No signal" and my ps3 doesn't have any light on, needing two clicks on the button to appear red light and then turn on again.

**Comment by requeijaum** [comment]
Be very careful about trying to boot PS2 Games using PS3HEN. I read somewhere @ PSX-Place forums that ManaGunZ would write some stuff to /dev_blind and render your PS2 Classics unbootable.

I don't know the current status with PS3HEN v2, though.

**Comment by Sakurakun5** [comment]
PS2 iso is not supported by hen u need convert games to PS2 Classics and resign them using PS3xploit Resigner.

**Comment by DiogoSilva48** [comment]
> Be very careful about trying to boot PS2 Games using PS3HEN. I read somewhere @ PSX-Place forums that ManaGunZ would write some stuff to /dev_blind and render your PS2 Classics unbootable.
> 
> I don't know the current status with PS3HEN v2, though.

Maybe, that's why, I will try to wipe my HDD and try again.



> PS2 iso is not supported by hen u need convert games to PS2 Classics and resign them using PS3xploit Resigner.

As I said in the post, I used that method you are saying after having HEN installed and the ps3 just turned off with no lights.

**Comment by Sakurakun5** [comment]
> As I said in the post, I used that method you are saying after having HEN installed and the ps3 just turned off with no lights.

i think u doing something wrong watch youtube video how to do that

**Comment by Sakurakun5** [comment]
> As I said in the post, I used that method you are saying after having HEN installed and the ps3 just turned off with no lights.
Install PS2 Classic from PSN and check if official game from sony will work if not something is wrong with your firmware or console.I recommend reinstaling firmware install OFW 4.84 then HFW 4.84 and then install HAN then HEN 2.0 and try again :).

**Comment by Sakurakun5** [comment]
Use component cable instead of HDMI.Meybe that the reason.

**Comment by DiogoSilva48** [comment]
> > As I said in the post, I used that method you are saying after having HEN installed and the ps3 just turned off with no lights.
> 
> Install PS2 Classic from PSN and check if official game from sony will work if not something is wrong with your firmware or console.I recommend reinstaling firmware install OFW 4.84 then HFW 4.84 and then install HAN then HEN 2.0 and try again :).

Already tried that but I will try again.

> Use component cable instead of HDMI.Meybe that the reason.

Can't be that since the console literally turns off.

**Comment by Sakurakun5** [comment]
> Can't be that since the console literally turns off.

Before u install firmware format hdd on your pc :)

**Comment by DiogoSilva48** [comment]
> > Can't be that since the console literally turns off.
> 
> Before u install firmware format hdd on your pc :)

lol, I know how it's done, I've done it multiple times for HAN

**Comment by delanolima** [comment]
@DiogoSilva48, usa esse pkg que fiz pra corrigir o problema com jogos de PS2. Só precisa habilitar dev_blind e habilitar o HEN e instalar o PKG.
http://www.mediafire.com/file/19buqfz40d72w4b/PS2_Classics_FIX_by_Vingdel.rar/file

**Comment by DiogoSilva48** [comment]
Thanks for the help, I had fixed it before and forgot to close the issues.

**Comment by FM1337** [comment]
@DiogoSilva48 what was the solution?
