### ISSUE TITLE
Sony Pulse Wireless headset not working with HEN enabled

### ISSUE THREAD

**Issue by MrNumberSix** [PS3Xploit/PS3HEN#20]
PS3 UltraSlim 4.85 HFW, HEN 3.0.0.
My Sony Pulse Elite headset does not receive any sound ingame when HEN is enabled. 
If HEN is not enabled, it works fine.
This headset uses a USB dongle for wireless connection, so maybe it's a conflict with how HEN handles the USB ports?

It only stops working when ingame, on XMB all sound is working. 
The PS3 still recognises the headset as connected, even without sound.

Issue was not present on the last "HAN" build I used a few months ago.

**Comment by Joonie86** [comment]
[PS3HEN_485.zip](https://github.com/PS3Xploit/PS3HEN/files/3753476/PS3HEN_485.zip)
Can you download and replace the attached payload file with yours to see this can resolve your issue?

dev_hdd0/hen/ should be where your payload is located.

**Comment by MrNumberSix** [comment]
Hi,
couldn't find "hen" folder or PS3HEN.BIN file inside **dev_hdd0/**, only in **/dev_flash**
But using a file manager homebrew I wasn't able to do anything with "PS3HEN.BIN" (I assume it's because HEN is running).
How do you suggest replacing the file?

**Comment by Itroublve** [comment]
He meant /dev_flash and you can try removing the PS3HEN.BIN from there and putting this new one.

**Comment by Itroublve** [comment]
And also, you can't remove or write things to dev_flash so use dev_rewrite!

**Comment by MrNumberSix** [comment]
**It worked!**

was able to replace _PS3HEN.BIN_ using _dev_rewrite_ as suggested, md5 hash checks (9a7114a14d6a3b6d9cb95ee14f4baab4).
sound in Pulse headset now works with HEN enabled.

**Comment by MrNumberSix** [comment]
Thank you guys very much.
