### ISSUE TITLE
Sony Pulse Elite Headset not working (again)

### ISSUE THREAD

**Issue by MrNumberSix** [PS3Xploit/PS3HEN#23]
My Pulse Elite Headset is currently not working again. I previously had a similar problem that was solved with a alternative build of PS3HEN, this thread:
https://github.com/PS3Xploit/PS3HEN/issues/20

It worked for a while, but at some moment it stopped receiving sound:
-The headset syncs up correctly with the PS3, but no sounds comes out, HEN enabled or not, both in XMB and ingame.
-Testing the headset's mic in Settings/Accessory Settings/Audio Device Settings returns spoken audio to the headset's speakers like normal (I can hear my voice in this test mode), which confirms the accessory is property synced with the PS3, but the system's audio is muted.
-Audio works when playing PS2 games (PS2classics mode), the only instance where it works properly.
-The set works properly on a PC, using the same USB dongle.

What I tried:
-Turning "Heatset Audio Extension" off than on again
-Reinstalling HEN
-Reinstalling OFW 4.85 (still no sound even on OFW)
-Reinstalling HFW 4.85 and HEN again
-Filesystem Restore
-Database Rebuild
-Restoring Default Settings on PS3
-Device reset on both dongle and headset
-Firmware reinstall through Sony's official PS3 app for the accessory

Anything short of a Factory Reset of the PS3... Nothing seems to work.

The problem seams to be with some user-unaccessible configuration with the PS3 itself, unfortunately I don't have access to a second PS3 at the moment for testing, but it works with a Windows PC as normal.
Since I had a similar problem before, I assume it has something to do with HEN.

**Comment by Joonie86** [comment]
If your headset doesn't work on OFW, the issue is not related to HEN. Please test your PC and other PS3s to ensure you have a working headset.

**Comment by MrNumberSix** [comment]
The headset works perfectly on this PS3 when in PS2 game mode, and also in any PC I test in.
My question is, could it be related to the alternative HEN build from thread https://github.com/PS3Xploit/PS3HEN/issues/20 ?
The issue seams to be some configuration on the PS3 that mutes the audio that should go to the USB dongle.

**Comment by Joonie86** [comment]
> The headset works perfectly on this PS3 when in PS2 game mode, and also in any PC I test in.
> My question is, could it be related to the alternative HEN build from thread #20 ?
> The issue seams to be some configuration on the PS3 that mutes the audio that should go to the USB dongle.

HEN issue should only occur when HEN is enabled. In your case it happens without HEN. We removed that buggy HEN patch that breaks the compatibility with your headset. So it's not related at all.

**Comment by MrNumberSix** [comment]
> > The headset works perfectly on this PS3 when in PS2 game mode, and also in any PC I test in.
> > My question is, could it be related to the alternative HEN build from thread #20 ?
> > The issue seams to be some configuration on the PS3 that mutes the audio that should go to the USB dongle.
> 
> HEN issue should only occur when HEN is enabled. In your case it happens without HEN. We removed that buggy HEN patch that breaks the compatibility with your headset. So it's not related at all.

Ok then, I'll keep trying. Thank you guys for your time.
