### ISSUE TITLE
[Request] compatibility with cobra ODE

### ISSUE THREAD

**Issue by bajolzas** [PS3Xploit/PS3HEN#24]
Sorry if this is the wrong place to ask, but i'd like to know if it is possible for ps3hen to be compatible with cobra ode, without the use of swap disc.
This could mean compatibility with ofw 4.55, or hfw 4.84/5 modified for ode to not require swap disc (if I remember right there were cfw that allowed ode to work without swap disc past 4.55, not sure if the same can be done on hfw).

**Comment by miatmax** [comment]
I have installed ps3hen 3.0.2 on my ps3 super slim with cobra ode, now it work with a ps3 with CFW, so i don't need swap disc.
