### ISSUE TITLE
headset sound issue

### ISSUE THREAD

**Issue by HyperSin** [PS3Xploit/PS3HEN#25]
idk if this is a hen issue or a hfw issue but before i installed hfw on the original system the ps3 game sound would come through the tv and people with mics would come through the headset, now the game and voices are coming through the headset, can someone help me revert it back to normal so i can only hear game on tv and voices on headset?

**Comment by PS3Xploit** [comment]
I believe this issue was resolved, or the patch has been disabled. If not, please comment below

**Comment by PS3Xploit** [comment]
closed. Feature may get moved to xai plugin, but was disabled a while back.
