### ISSUE TITLE
v3.0.1 multiman and irisman black screen (potential signing issue ?)

### ISSUE THREAD

**Issue by RRPRIME** [PS3Xploit/PS3HEN#29]
PS3 SuperSlim CEH-4000
V4.86 
HEN v3.0.1

Managers tried:
multiMAN (BASE) | v04.85.01
Unofficial multiMAN | v04.84 HEN
IRISMAN Full Edition | v4.86.3

HEN appears to start fine every time but the managers freeze at a black screen when they start 70-80% of time time. (is there a way to further debug this ?)

**Comment by The-SamminAter** [comment]
Same on HEN v3.0.2.

**Comment by osteinjr** [comment]
Same on HEN v3.0.3.

**Comment by PS3Xploit** [comment]
Is this issue still present? Can you provide socat logs (using debug version of HEN)?

**Comment by RRPRIME** [comment]
@PS3Xploit hello,
Where could you please help me out, from where can I get the Debug version ? and where are the logs stored ?

Thanks !

**Comment by PS3Xploit** [comment]
Debug version is in this repo and in Developer ZIP on ps3xploit.com

**Comment by RRPRIME** [comment]
@PS3Xploit mean sure you can close it (I this is a free service) without giving any help in debugging this issue (how to extract the needed logs), just pointing to a debug build.
