### ISSUE TITLE
if a game folder is mounted, the CFW2OFW game doesn't work

### ISSUE THREAD

**Issue by LouisGarry** [PS3Xploit/PS3HEN#30]
https://www.psx-place.com/threads/why-if-there-is-a-game-folder-mounted-cfw2ofw-games-dont-work.30312/

**Comment by PS3Xploit** [comment]
is this still something that needs looked into?

https://www.psx-place.com/threads/why-if-there-is-a-game-folder-mounted-cfw2ofw-games-dont-work.30312/#post-253621

**Comment by LouisGarry** [comment]
Thanks for your repply.

Yes, and one more thing, game folders like Metal Gear Solid V: The Phantom Pain don't work like CFW, have to install game updates.
Hopefully it can be fixed.
