### ISSUE TITLE
Using ‘★ Enable Hen’ crashes (the) PS3

### ISSUE THREAD

**Issue by The-SamminAter** [PS3Xploit/PS3HEN#32]
I’ve installed the latest version of HEN from ps3xploit, and am (trying to) enable it on a PS3 Slim running HFW 4.87.

When I try to enable HEN via the ‘Enable HEN’ button in the games section of XMB, the PS3 freezes. The only way I’m currently able to enable HEN is from ps3xploit’s HEN installer/enabler.

It used to work, when the HEN Enabler has a different/new look/logo, but that page no longer exists on ps3xploit, and never existed here on HEN’s GitHub (I checked the commits).

**Comment by The-SamminAter** [comment]
May I ask why the `★ Enable Hen` section of `/dev_rewrite/vsh/resource/explore/category_game.xml` from when I install HEN via ps3xploit, and from the same file from `Latest_HEN_Installer_3.0.2_signed-487C.pkg` (from HEN v3.0.2 Release Files (4.87 HFW)) are different?

**Comment by PS3Xploit** [comment]
These issues are more suited for PSX-Place forums.

the packages used are as follows

Release: Latest_HEN_Installer_signed.pkg
Manual Installer: HEN.pkg
Developer ZIP: Latest_HEN_Installer_3.0.2_signed-487C.pkg

i just verified all of them on server and the pkg md5 is 98fd51c7722fad1aa5df6d6bf468095adf90f7ca
