### ISSUE TITLE
If hen is enabled and then click hen icon again on ps3, it will cause a root

### ISSUE THREAD

**Issue by sunnyqeen** [PS3Xploit/PS3HEN#37]
It seems hen does not check if it is enabled or not.
It still try to enable, then with a failed reboot.

**Comment by PS3Xploit** [comment]
This issue will hopefully be resolved in a future update. There are a few small projects that are looking into this. and ways to refresh the icon and xml, or remove the entry after enabling, so it cannot be triggered more than once.
