### ISSUE TITLE
HEN Debug FTP problems

### ISSUE THREAD

**Issue by PS3-4K-Pro** [PS3Xploit/PS3HEN#38]
The DEBUG version of HEN, when transferring hude files over FTP (ANDROID) using webman or multiman, the console will freeze.

Confirmed by me and some friends

Normal version is ok

**Comment by PS3Xploit** [comment]
Thanks for the report. Not sure if this issue will be solved, due to the low amount of users of DEBUG version.

**Comment by Joonie86** [comment]
How huge? I transferred a 25GB iso last night while my debug console was on with no issue. I used Filezilla on Win11 though. Closing this issue now until the issue’s confirmed again.
