### ISSUE TITLE
CCAPI problem

### ISSUE THREAD

**Issue by Elenimotoon** [PS3Xploit/PS3HEN#41]
This new version of Hen has the issue that CCAPI functions parcially works, because you can connect a PC to your PS3 system, but in-game changes that you made with a tool for example doesn't make any visual changes, but appears in upper right corner that your pc is connected. 

FTP works well in my case, but not CCAPI.

**Comment by PS3Xploit** [comment]
CCAPI IS NOT SUPPORTED BY HEN!
