### ISSUE TITLE
The act.dat backup/restore function does not work

### ISSUE THREAD

**Issue by KrisztianKende** [PS3Xploit/PS3HEN#44]
I tried everything but act.dat (generated with Apollo Save Tool) won't restore from /dev_hdd0/home/00000001/exdata/act.bak. I found the code in henplugin/main.c and I don't see any problem, but it just doesn't work.
Act.dat is restored (copy act.bak) when I load the webMAN Mod plugin (lite or not), even if the boot_init.txt doesn't exist. But without it, act.dat will be missing, although act.bak does exist.

Tested on CECH-4004C (HDD) and CECH-4304A (16GB eMMC + HDD) Super Slim consoles with system software version 4.89 HFW.

**Comment by bucanero** [comment]
oh, you're on 4.89, if not you could try some other builds, like:
https://www.psx-place.com/threads/apollo-save-tool-development-thread.27964/page-28#post-305964

or this one:
https://www.mediafire.com/file/2em2mto1ywar69x/PS3HEN_BIN-act.zip/file

but those are not for 4.89, so you need to use webman mod or restore manually

**Comment by KrisztianKende** [comment]
I'm on 4.89, so older alternative builds are out of the question. But I thought this was already resolved in the latest official build. I can see it in the source code and in the changelog (_Added act.dat Backup/Restore feature_).
Could it be malfunctioning or not supported after all?

**Comment by bucanero** [comment]
I have built a new test version for 4.89, and did some changes to the `act.dat` restore. You can get the `PS3HEN.BIN` here:
[PS3HEN.zip](https://github.com/PS3Xploit/PS3HEN/files/9365638/PS3HEN.zip)

you need to unzip and rename to PS3HEN.BIN, then overwrite the current PS3HEN.BIN on your PS3. 
**To avoid risks, test it ONLY on the super-slim 4004C, in the worst case scenario you can always format HDD, reinstall HFW and start again.** (avoid the 16gb eMMC)

If you test and confirm the file is restored as expected, then I'll submit changes for the next HEN release.

**Comment by KrisztianKende** [comment]
Thanks Damián, I tested your modified `PS3HEN.BIN` file, and the act.dat restore function seems to work properly. ;-)

**Comment by bucanero** [comment]
> Thanks Damián, I tested your modified `PS3HEN.BIN` file, and the act.dat restore function seems to work properly. ;-)

Great to hear it's working 👍  I'll submit a PR with the changes and link it to this issue.
