### ISSUE TITLE
website down since like 2017?

### ISSUE THREAD

**Issue by rasphan-123** [PS3Xploit/PS3HEN#47]
basicly, i just got a ps3 and i want to hack it and the website for ps3xploit.com AND ps3xploit.me are down.
![Screenshot 2023-02-01 152630](https://user-images.githubusercontent.com/76595690/216156003-3f006b26-0f8d-460b-abe1-84d266c22a06.png)

**Comment by esc0rtd3w** [comment]
this has been resolved. ps3xploit.me is the main site now and is online
