### ISSUE TITLE
Updating HEN gives error code 80029563.

### ISSUE THREAD

**Issue by LinoBigatti** [PS3Xploit/PS3HEN#48]
When enabling HEN, it downloads the latest signed pkg fine, but when it tries to install it, it gives me an `80029563` error. As far as I could gather from a search, this is a signing error. How should I resolve it?

**Comment by nikolaevich23** [comment]
> When enabling HEN, it downloads the latest signed pkg fine, but when it tries to install it, it gives me an `80029563` error. As far as I could gather from a search, this is a signing error. How should I resolve it?
[Explanation here](https://www.psx-place.com/threads/ps3-hen-20-2-0.39538/)
You can reinstall from the address https://ps3addict.github.io/ - by moderator psx-place

**Comment by LinoBigatti** [comment]
I believe my version isnt compromised, so Ill just disable automatic updates. 
Thanks for the help, Ill be closing this issue now.
