### ISSUE TITLE
A question about stage0

### ISSUE THREAD

**Issue by Yoti** [PS3Xploit/PS3HEN#49]
As I saw here https://github.com/PS3Xploit/PS3HEN/blob/master/stage0_file/main.c#L30 this workaround only needed for 4.82 DEX, 4.84 DEX and 4.82 CEX. Does stage0 works on 4.84 CEX without workaround, but it still needed for 4.84 DEX?

**Comment by Joonie86** [comment]
I think this was needed when we used to have older stackframe. I don’t think we need this anymore if you back port the current stackframe. There’s no reason why 4.82 CEX would need this with the current stackframe but I can’t quite remember what exactly we did for DEX variants.
