### ISSUE TITLE
PS3HEN 3.2.0 on HFW 4.90 freezing

### ISSUE THREAD

**Issue by Zariaa27** [PS3Xploit/PS3HEN#52]
Hey! I've installed latest versions of both HEN and HFW but now when enabling HEN, the console freezes. May anyone help me with this quite annoying issue?

**Comment by Joonie86** [comment]
Hold R2 while enabling HEN then update your webMAN MOD to the latest version.

**Comment by Zariaa27** [comment]
That still does not work, is there another workaround

**Comment by Joonie86** [comment]
make an empty boot_plugins.txt and put it on a working USB drive and leave it plugged into your PS3 and enable HEN. if nothing works then format your HDD.

**Comment by Zariaa27** [comment]
Worked one time, then rebooted and the HEN icon dissappeared. Sorry for causing y'all a hassle btw lol

**Comment by Joonie86** [comment]
> Worked one time, then rebooted and the HEN icon dissappeared. Sorry for causing y'all a hassle btw lol

Create a new user profile.
