### ISSUE TITLE
HEN Enabler button dissappear after quit some app/game

### ISSUE THREAD

**Issue by UJNGAD** [PS3Xploit/PS3HEN#54]
Hi, need advice here.
HEN Enabler seem not unfamiliar on Google but it is first time for me after update to hfw 4.90.1 and HEN 3.2.0. It was not issue for me, untill two case bellow decide me to write here.
1. Rambo The Video Game from NoPayStation did not work and force me to quit the game, that first time I missing "HEN Enabler" button, restart the system got back the button and relunch the game just to got stuck on loading then force to quit the game, again "HEN Enabler" button dissapeared. Reinstall the game from another site working without issue so I was though it because the defect game from NoPaystation. I got some not working game from NoPaystation but it never end with missing the button when quit on failed load.
2. Recently after hundreed time ran prepISO to mount pkg from ExFat, I got "HEN Enabler" dissapear but webMAN still working, I able to install game and run them without restart the system. It seem the system in "HEN Enable" state just missing the "HEN Enabler" button. Restart the system bring back the button.
Thank you

**Comment by esc0rtd3w** [comment]
That is normal behavior starting with version 3.2.0. Once the XMB is refreshed, the Enable HEN icon disappears, asa its not needed anymore, until reboot.
