### ISSUE TITLE
ps3hen 3.2.1 keeps freezing my ps3

### ISSUE THREAD

**Issue by abcbgaming** [PS3Xploit/PS3HEN#55]
so i have a ps3 that has ps3hen 3.2.1 on it, but every time i try to do anything on it, it freezes and i have to unplug the power cord.  i have tried reinstalling the homebrew multiple times, and even switched hard drives.  still the same thing.  can someone help me?

**Comment by DYRM3006** [comment]
Reinstall original firmware,  then redo hen hfw firmware worked for me

**Comment by abcbgaming** [comment]
did that multiple times, still happening

**Comment by aldostools** [comment]
You have to install the latest version to avoid freeze issues. You can use the online updater or download the latest installer from GitHub or Brewology.

Current version is 1.47 44 (if you have 1.47.43 or older you will get freeze)

Put an empty `boot_plugins.txt` in the root of a pendrive, connect it to an USB port of the PS3 to disable temporarily the load of plugins until are able to update or install the latest version. Unplug the pendrive or delete the empty file to let the new version load the next time you enable HEN.

**Comment by abcbgaming** [comment]
can you send a link to the latest version of it please?

**Comment by aldostools** [comment]
> can you send a link to the latest version of it please?

https://github.com/aldostools/webMAN-MOD/releases
or
https://store.brewology.com/ahomebrew.php?brewid=310

**Comment by abcbgaming** [comment]
i just tried to update the thing, it worked for like, 5 minutes and froze again.

**Comment by DYRM3006** [comment]
Are u installing webman? Or what are u using?

**Comment by abcbgaming** [comment]
ok, so webman uninstalled itself thats why it froze, but now it won't reinstall at all.  what's going on?

**Comment by DYRM3006** [comment]
Restart PS3 fully and enable hen then try again or delete folder for webman

**Comment by esc0rtd3w** [comment]
> there is no webman folder though

The sprx are in /dev_hdd0/plugins/

Im trying to understand your issue. Did you update from a previous build of PS3HEN or 3.2.1 is a fresh install? I am assuming you are on 4.90 HFW?

The 3.2.1 build does check for webman, but only if installing from HTML. If you had a previous version of PS3HEN installed, such as 3.2.0, then the auto-update would trigger by default, from XMB, but webman check does not delete boot_plugins.txt, like it does from HTML. This check may be added in next release, if this is still causing an issue.

From a clean install of HFW and a clean install of PS3HEN, using Auto Installer from ps3xploit.me, you should have zero issues.

If you can provide any additional information, that may help with future builds addressing this problem.

**Comment by esc0rtd3w** [comment]
please try with 3.2.2 release
