### ISSUE TITLE
HEN_UPD.PKG is broken

### ISSUE THREAD

**Issue by dimagenarious** [PS3Xploit/PS3HEN#58]
Hello! I've tried to install PS3HEN using several offline methods. I've placed PS3HEN.BIN and HEN_UPD.PKG on a usb drive. I use ps3hen_enabler_usb000.html to get it working. HEN start successfully and tries to install HEN_UPD.PKG. But system reboots before package installation is finished. I think PKG installation detection is broken in version 3.2.2. In version 3.2.0 everything is working fine.

**Comment by KneesDev** [comment]
Use the online method from ps3xploit.me

**Comment by esc0rtd3w** [comment]
> Hello! I've tried to install PS3HEN using several offline methods. I've placed PS3HEN.BIN and HEN_UPD.PKG on a usb drive. I use ps3hen_enabler_usb000.html to get it working. HEN start successfully and tries to install HEN_UPD.PKG. But system reboots before package installation is finished. I think PKG installation detection is broken in version 3.2.2. In version 3.2.0 everything is working fine.

Thank you for pointing this out. The method was changed in 3.2.2 for detecting when the installer was done. I will look into this.

**Comment by esc0rtd3w** [comment]
The automatic reboot has been removed for HEN_UPD.PKG because of issues. It has been replaced by a popup message that tells user to reboot manually.

https://github.com/PS3Xploit/PS3HEN/commit/00a262762bb49000b652cc4ab6ca0f31a06748cb
