### ISSUE TITLE
String customisation

### ISSUE THREAD

**Issue by RFNS13** [PS3Xploit/PS3HEN#62]
Hey!
I was used to editing category_game.xml from the xmb folder and change the "★ Enable HEN" string to something my daughter can read and understand when she boots the PS3, but updating to fw 4.90 and HEN 3.2.2, I can't find that specifig string anywhere.... Can someone point me in the right direction?
Thanks!

**Comment by aldostools** [comment]
In HEN 4.90 the file `category_game.xml` now is linked to the external file: `/dev_hdd0/hen/xml/hen_enable.xml`

In that file you will find the title name:
`<Pair key="title"><String>★ Enable HEN</String></Pair>`

**Comment by RFNS13** [comment]
Thanks!!
But... are there any extra steps to access that file? Ftp transfer to my desktop always returns an error, and if i acess webmansetup via web, go to files and click it, it opens a blank/empty xml....

**Comment by aldostools** [comment]
That file could be remapped to some file or folder in dev_flash which is read only.

Try using http://0/remap.ps3 to unmap all mapped files. I recommend to reboot after replace the file to restore the mappings.

**Comment by aldostools** [comment]
Another option is to edit the XML found in the HEN installer package, then reinstall HEN with the modified file.

**Comment by RFNS13** [comment]
Thanks for your effort, but no luck.... I tried both remap.ps3 and unmap.ps3, the file is there, but it's not 
![1](https://github.com/PS3Xploit/PS3HEN/assets/67279660/52629309-cf65-42b1-aaa8-b33a2351666f)
![2](https://github.com/PS3Xploit/PS3HEN/assets/67279660/ee32ef61-5f08-4fc9-a32d-98b05bfc1ba2)

**Comment by nikolaevich23** [comment]
> RFNS13
the fact is that this file is mounted on an empty one after running hen

[hen_enable.xml.zip](https://github.com/PS3Xploit/PS3HEN/files/12516145/hen_enable.xml.zip)

**Comment by esc0rtd3w** [comment]
> Hey! I was used to editing category_game.xml from the xmb folder and change the "★ Enable HEN" string to something my daughter can read and understand when she boots the PS3, but updating to fw 4.90 and HEN 3.2.2, I can't find that specifig string anywhere.... Can someone point me in the right direction? Thanks!

You can hold L2 while HEN is loading, or use HFW Tools menu Developer options to disable Remap, then you can edit the file
