### ISSUE TITLE
PSP Launcher needs license to launch

### ISSUE THREAD

**Issue by alfredox123** [PS3Xploit/PS3HEN#63]
I tried every psp launcher i could find on internet on hen 3.2.2 but none works, it always says that i need license to launch it.

Im i missing something?

**Comment by aldostools** [comment]
I found this comment in https://www.reddit.com/r/ps3homebrew/comments/8qjgm1/psp_launcher_this_content_can_be_used_if_you/

> I was getting the "renew license" message when using PSP Launcher Fixed jjkkyu v2 as well. Turns out, webman wasn't actually mounting the psp isos. I installed the original COBRA PSP Launcher, rebooted, and webman actually started mounting the games. The launcher worked! After that, I installed the newer launchers (jjkkyu's and the remaster one). They both work.
>
> Apparently the newer launchers don't install everything that the original launcher did. Side Note/Background: After fixing this issue, I remembered that there was a PSP Launcher in my XMB after I first hacked my PS3. I deleted it back then because I didn't think I'd ever be interested in a PSP game. That's probably why I had this issue to begin with.

Also you could try deleting the current PSP launchers and re-installing these ones:
[PSP_Minis_Launcher.pkg](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.45/PSP_Minis_Launcher.pkg)
[PSP_Remasters_Launcher.pkg](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.45/PSP_Remasters_Launcher.pkg)

**Comment by aldostools** [comment]
This is another thread with the same issue:
https://github.com/PS3Xploit/PS3HEN/issues/11

**Comment by alfredox123** [comment]
Yes I read and tested those things but I still get the license issue with psp launchers, gonna try the pkg you linked to see if it does something, bat I'm on 4.90 hfw

**Comment by aldostools** [comment]
I don't have that issue on CFW Evilnat 4.90. It could be an issue with your RIF licenses or with the latest HEN payload.
I recommend that open a thread in PSX-PLACE or an issue PS3Xploit repository.

**Comment by alfredox123** [comment]
Ive been trying to join psx-place since the last time i told you, but i cant activate my account i dont recieve email for verification i try to contact them but i dont get any response.

**Comment by aldostools** [comment]
Did you check the spam folder? Maybe your mail is blocking the verification email.
At least ask in PS3Xploit repository https://github.com/PS3Xploit/PS3HEN/issues/11

**Comment by alfredox123** [comment]
yes i checked spam, i guess my email is blocking it, which one is the mail for verification, to check if im blocking it.

**Comment by aldostools** [comment]
There are other places where you can ask about HEN: reddit, github, discord, X (twitter), etc.

I'm not a HEN user. Therefore I don't have much experience with that payload. That's why I suggest to ask in another place.

**Comment by esc0rtd3w** [comment]
You can post the issue here or as Aldo suggested

https://www.psx-place.com/threads/support-thread-ps3hen-bugs-problems-and-other-issues.37327/

**Comment by esc0rtd3w** [comment]
This has been resolved in upcoming release 3.3.0 for 4.91 firmware. If there are other issues, please open a new issue.

https://github.com/PS3Xploit/PS3HEN/pull/68

**Comment by aldostools** [comment]
There is a thread opened in webMAN MOD related this issue. Check the post from @LuanTeles at the bottom.
https://github.com/aldostools/webMAN-MOD/issues/933

**Comment by esc0rtd3w** [comment]
Basically aldos original fix but modified. All seems to be working now

https://github.com/PS3Xploit/PS3HEN/commit/6ff8cfe427f7e2cf683513771808a0e62f4fe866
