### ISSUE TITLE
Unable to visit http://www.ps3xploit.me from my ps3 super slim

### ISSUE THREAD

**Issue by Manveer-Singh-99** [PS3Xploit/PS3HEN#64]
Hey guys i was trying to get HEN working on the HFW on my super slim ps3 after the 4.90.1  update and discovered that i was getting the error “ the page cannot be displayed 80710a06”. Ive restarted the ps3, did the update twice, cleared out the browser, used wired and wireless internet. I was wondering if i could use the source code of the site to create a local web server maybe? Please help me out, if i cant get back the “Enable HEN” option i’ll be losing all my save data and 500 gigabytes worth of games which ive put onto my hard disk.

**Comment by aldostools** [comment]
The website ps3xploit.me is working. Check if it is your Internet connection in the PS3 or if your ISP is blocking the site.

Yes, you can configure a local web server with the HEN installer or use https://ps3addict.github.io

**Comment by StrawFox64** [comment]
try putting an empty file on your USB stick called boot_plugins.txt and insert it in /dev_usb000 (the closest to the bluray reader)

**Comment by trickshot615** [comment]
i tried the alternate installer, but it keeps failing what do i do?
