### ISSUE TITLE
Irisman problem

### ISSUE THREAD

**Issue by lsizquierdo** [PS3Xploit/PS3HEN#7]
When you try to load a PS3 backup iso with Irisman_HEN version, the system shutdown.

**Comment by Joonie86** [comment]
Please use this build.

https://mega.nz/#!jVBTgA4L!Iu9e5pNlrPNldVRfOCFKi15V_wisYYRcDek-1F70N8U

and follow this thread for further information.

https://www.psx-place.com/threads/henbrew.24466/
